/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diego Canon
 */
public class Ejecucion extends javax.swing.JFrame {

    /**
     * Creates new form Ejecucion
     */
    public Ejecucion() {
        initComponents();
        setSize(1280, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelPersonajes = new javax.swing.JPanel();
        JArqueto = new javax.swing.JButton();
        JCaballero = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setSize(new java.awt.Dimension(1280, 800));

        PanelPersonajes.setBackground(new java.awt.Color(153, 153, 153));
        PanelPersonajes.setPreferredSize(new java.awt.Dimension(1280, 800));
        PanelPersonajes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JArqueto.setBackground(new java.awt.Color(0, 102, 102));
        JArqueto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen arquero (1).png"))); // NOI18N
        JArqueto.setPreferredSize(new java.awt.Dimension(40, 18));
        JArqueto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JArquetoActionPerformed(evt);
            }
        });
        PanelPersonajes.add(JArqueto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 160, 240));

        JCaballero.setBackground(new java.awt.Color(0, 102, 102));
        JCaballero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen arquero (1).png"))); // NOI18N
        JCaballero.setPreferredSize(new java.awt.Dimension(40, 18));
        JCaballero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCaballeroActionPerformed(evt);
            }
        });
        PanelPersonajes.add(JCaballero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, 240));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelPersonajes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void JArquetoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.out.println("Arquero");
    }                                        

    private void JCaballeroActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PanelPersonajes.setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejecucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejecucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JArqueto;
    private javax.swing.JButton JCaballero;
    private javax.swing.JPanel PanelPersonajes;
    private javax.swing.JButton jButton1;
    // End of variables declaration                   
}
